version: '3.8'
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: hospital_management
      POSTGRES_USER: Venki
      POSTGRES_PASSWORD: Venki@034
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/l9_iot_platform.sql:/docker-entrypoint-initdb.d/l9_iot_platform.sql
    restart: always

volumes:
  postgres_data:
